POST http://localhost:3000/idp/error HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYWQ1MjFlYTJiYmM2MTRjN2EwNjZlNSIsImtpbmQiOiJhY2Nlc3NfdG9rZW4iLCJpYXQiOjE2Mjg1NzI3MjksImV4cCI6MTYyODY1OTEyOX0.PP6FcLU3zscB4h5t2ye51iYZyDwMdBDkv1s66YgN1l0

{  
  "node_id": "",
  "type": "Error",
  "action": "string",
  "request_id": " 6a40df95c0ad40e9fe83a485c2b13b64992093761420b48bb3f576930ad89a85 ",
  "error": {
    "code": 0,
    "message": "sds"
  }
}

###
GET http://localhost:3000/flushStat HTTP/1.1
Content-Type: application/json
X-Rtid: IOS-200129aWZtbSUCCESS
X-Session-Id: Gjs4zupGo0jxZchGMAoAAA
X-Tid: IOS-200129aWZtb96IqMEw 