POST http://localhost:3000/services/v1/identityServiceReject HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYWQ1MjFlYTJiYmM2MTRjN2EwNjZlNSIsImtpbmQiOiJhY2Nlc3NfdG9rZW4iLCJpYXQiOjE2MzUxODE0MTksImV4cCI6MTYzNTI2NzgxOX0.2_O1RroqKweJb50WR7cNcxIGrLhTInzB4cG6FAWC9-4

{  
            "identityType": "citizen_id",
            "identityValue": "1377777776879"
}
